if(EXISTS "/Users/joshc/projects/toy_dfs/test/test_datanode_service[1]_tests.cmake")
  include("/Users/joshc/projects/toy_dfs/test/test_datanode_service[1]_tests.cmake")
else()
  add_test(test_datanode_service_NOT_BUILT test_datanode_service_NOT_BUILT)
endif()
